# Generated by Django 3.0.2 on 2020-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=80)),
                ('phone', models.IntegerField()),
                ('category', models.CharField(choices=[('NR', 'Non IIT Roorkee'), ('IR', 'IIT Roorkee'), ('PF', 'Professor')], default='NR', max_length=2)),
                ('city', models.TextField(max_length=50)),
                ('invitecode', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('MM', 'Male'), ('FM', 'Female'), ('OO', 'Others')], default='MM', max_length=2)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
